// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using VitaOrbitApi.Data;

#nullable disable

namespace VitaOrbitApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VitaOrbitApi.Models.Alert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                    b.Property<int?>("HealthRecordId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int?>("SymptomRecordId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TypeAlert")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("AlertId");

                    b.HasIndex("HealthRecordId");

                    b.HasIndex("SymptomRecordId");

                    b.HasIndex("UserId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("VitaOrbitApi.Models.Emergency", b =>
                {
                    b.Property<int>("EmergencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmergencyId"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("EmergencyId");

                    b.HasIndex("UserId");

                    b.ToTable("Emergencies");
                });

            modelBuilder.Entity("VitaOrbitApi.Models.EnvironmentalCondition", b =>
                {
                    b.Property<int>("EnvironmentalConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnvironmentalConditionId"));

                    b.Property<string>("AirQuality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<decimal>("Altitude")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("AtmosphericPressure")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("EnvironmentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<decimal>("ExternalTemperature")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Humidity")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("RadiationLevel")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("EnvironmentalConditionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EnvironmentalConditions");
                });

            modelBuilder.Entity("VitaOrbitApi.Models.HealthRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthRecordId"));

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("BodyTemperature")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("HeartRate")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("HydrationLevel")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int>("OxygenSaturation")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("RiskClassification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<decimal>("SleepHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("HealthRecordId");

                    b.HasIndex("UserId");

                    b.ToTable("HealthRecords");
                });

            modelBuilder.Entity("VitaOrbitApi.Models.SymptomRecord", b =>
                {
                    b.Property<int>("SymptomRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SymptomRecordId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<decimal>("Intensity")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("RiskClassification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("SymptomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("SymptomRecordId");

                    b.HasIndex("UserId");

                    b.ToTable("SymptomRecords");
                });

            modelBuilder.Entity("VitaOrbitApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CurrentLocation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UserDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VitaOrbitApi.Models.Alert", b =>
                {
                    b.HasOne("VitaOrbitApi.Models.HealthRecord", "HealthRecord")
                        .WithMany("Alerts")
                        .HasForeignKey("HealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VitaOrbitApi.Models.SymptomRecord", "SymptomRecord")
                        .WithMany("Alerts")
                        .HasForeignKey("SymptomRecordId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VitaOrbitApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthRecord");

                    b.Navigation("SymptomRecord");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitaOrbitApi.Models.Emergency", b =>
                {
                    b.HasOne("VitaOrbitApi.Models.User", "User")
                        .WithMany("Emergencies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitaOrbitApi.Models.EnvironmentalCondition", b =>
                {
                    b.HasOne("VitaOrbitApi.Models.User", "User")
                        .WithOne("EnvironmentalCondition")
                        .HasForeignKey("VitaOrbitApi.Models.EnvironmentalCondition", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitaOrbitApi.Models.HealthRecord", b =>
                {
                    b.HasOne("VitaOrbitApi.Models.User", "User")
                        .WithMany("HealthRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitaOrbitApi.Models.SymptomRecord", b =>
                {
                    b.HasOne("VitaOrbitApi.Models.User", "User")
                        .WithMany("SymptomRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitaOrbitApi.Models.HealthRecord", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("VitaOrbitApi.Models.SymptomRecord", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("VitaOrbitApi.Models.User", b =>
                {
                    b.Navigation("Emergencies");

                    b.Navigation("EnvironmentalCondition");

                    b.Navigation("HealthRecords");

                    b.Navigation("SymptomRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
